In [1]:
import sys
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Add SRC folder path
sys.path.append(str(Path.cwd().parent / "src"))
from data_prep import load_and_prepare_data

In [2]:
# loading data for no smotenc
csv_path = "../data/external/FPA_FOD_Plus.csv"

X_train, Y_train, X_val, Y_val, X_test, Y_test = load_and_prepare_data(
    csv_path,
    smote_strategy="none"
)


Loading data with Polars...
File loaded into Pandas. Shape: (2302521, 308)

 No oversampling applied (dataset remains imbalanced).


In [3]:
print("Train shape:", X_train.shape, Y_train.shape)
# training rf
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=207,
    n_jobs=-1
)

Train shape: (1381512, 49) (1381512,)


In [4]:
print("\nTraining Random Forest...")
rf.fit(X_train, Y_train)

# evaluation metrics
print("\nValidation Results")
preds = rf.predict(X_val)

print("Accuracy:", accuracy_score(Y_val, preds))
print("\nClassification Report:\n", classification_report(Y_val, preds))
print("\nConfusion Matrix:\n", confusion_matrix(Y_val, preds))


Training Random Forest...

Validation Results
Accuracy: 0.9736506088980769

Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99    448361
           1       0.45      0.00      0.00     11185
           2       0.00      0.00      0.00       738
           3       0.00      0.00      0.00       220

    accuracy                           0.97    460504
   macro avg       0.36      0.25      0.25    460504
weighted avg       0.96      0.97      0.96    460504


Confusion Matrix:
 [[448348     13      0      0]
 [ 11163     22      0      0]
 [   728     10      0      0]
 [   216      4      0      0]]


/Users/nedim/miniforge3/envs/tf_cpu_mids/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/nedim/miniforge3/envs/tf_cpu_mids/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/nedim/miniforge3/envs/tf_cpu_mids/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mod